const colors = {
  light: {
    text: "#1A1A2E",
    tint: "#FF6B35",
    background: "#F8F9FA",
    foreground: "#1A1A2E",
    card: "#FFFFFF",
    cardForeground: "#1A1A2E",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    secondary: "#2D9CDB",
    secondaryForeground: "#FFFFFF",
    muted: "#F1F3F5",
    mutedForeground: "#6C757D",
    accent: "#28C76F",
    accentForeground: "#FFFFFF",
    destructive: "#EA5455",
    destructiveForeground: "#FFFFFF",
    border: "#E9ECEF",
    input: "#E9ECEF",
    warning: "#FF9F43",
    warningForeground: "#FFFFFF",
    temperatureColor: "#FF6B35",
    humidityColor: "#2D9CDB",
    fanColor: "#28C76F",
    heaterColor: "#FF4500",
    surface: "#F1F3F5",
  },
  dark: {
    text: "#E6EDF3",
    tint: "#FF6B35",
    background: "#0D1117",
    foreground: "#E6EDF3",
    card: "#161B22",
    cardForeground: "#E6EDF3",
    primary: "#FF6B35",
    primaryForeground: "#FFFFFF",
    secondary: "#2D9CDB",
    secondaryForeground: "#FFFFFF",
    muted: "#21262D",
    mutedForeground: "#7D8590",
    accent: "#3DD68C",
    accentForeground: "#0D1117",
    destructive: "#F85149",
    destructiveForeground: "#FFFFFF",
    border: "#21262D",
    input: "#21262D",
    warning: "#F0883E",
    warningForeground: "#FFFFFF",
    temperatureColor: "#FF6B35",
    humidityColor: "#2D9CDB",
    fanColor: "#3DD68C",
    heaterColor: "#FF4500",
    surface: "#1C2128",
  },
  radius: 12,
};

export default colors;
